// vue-boilerplate/src/App.vue
<template>
  <nav>
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link>
  </nav>
  <router-view/>
  <div class="overlay-tn"></div>
</template>

<script setup>
  import { onMounted, reactive } from 'vue'
  import { Client } from '@tokenscript/token-negotiator';
  import '@tokenscript/token-negotiator/dist/theme/style.css';

  const negotiatorObj = reactive({ client: undefined });

  onMounted(() => {
  negotiatorObj.client = new Client({
    type: 'active',
    issuers: [
      {
        collectionID: "penthouse-panther-club",
        collectionAddress: "ff846ef2eed57e5367cf8826e63f4d53fe28d28aa67417accb6e4b48cbd19136",
        onChain: true,
        collectionSymbol: "PPC",
        chain: "mainnet",
        blockchain: "solana",
      },
      {
        collectionID: "pixel",
        collectionAddress: "166424b16c4c7f40eb852f9eb2d0d6869a9ed7ac54a8e6afbd516676bfbbeb19",
        onChain: true,
        collectionSymbol: "PIXEL",
        chain: "mainnet",
        blockchain: "solana",
      },
      {
        onChain: true, 
        collectionID: "expansion-punks", 
        contract: '0x0d0167a823c6619d430b1a96ad85b888bcf97c37', 
        chain: 'eth',
        blockchain: "ethereum",
      },
    ],
    uiOptions: {
        openingHeading: "Open a new world of discounts available with your tokens.",
        issuerHeading: "Get discount with Ticket",
        repeatAction: "try again",
        theme: 'dark',
        position: "top-right"
    },
    unSupportedUserAgent: {
      authentication: {
        config: {
          metaMaskAndroid: true,
          alphaWalletAndroid: true,
          mewAndroid: true,
          imTokenAndroid: true,
        },
        errorMessage: "No Support for Authentication with this user agent. Try Chrome, Safari or Edge instead."
      },
      full: {
        config: {
          iE: true,
          iE9: true,
        },
        errorMessage: "This browser is not supported. Please try using Chrome, Edge, FireFox or Safari."
      }
    },
    safeConnectOptions: {
      url: "https://safeconnect.tokenscript.org",
      initialProof: false
    }
  });

  negotiatorObj.client.on("tokens-selected", (tokens) => {
    console.log(tokens);
  });

  negotiatorObj.client.on("token-proof", (proof) => {
    console.log(proof);
  });

  negotiatorObj.client.negotiate();
})
</script>

<style lang="scss">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

nav {
  padding: 30px;
}

nav a {
  font-weight: bold;
  color: #2c3e50;
}

nav a.router-link-exact-active {
  color: #42b983;
}
</style>

// angular-bare-bones-demo/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Client } from '@tokenscript/token-negotiator';
import { Issuer } from '@tokenscript/token-negotiator/dist/client/interface';

import issuersData from './issues';



@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
 

export class AppComponent implements OnInit {
  
  public issuers: Issuer[] = issuersData;
  public negotiator: Client;

  constructor() { 
    this.negotiator = new Client({
      type: 'active',
      issuers: this.issuers,
      uiOptions: {
          openingHeading: "Open a new world of discounts available with your tokens.",
          issuerHeading: "Get discount with Ticket",
          repeatAction: "try again",
          theme: "light",
          position: "bottom-right"
      },
      autoLoadTokens: 3,
      safeConnectOptions: {
          url: "https://safeconnect.tokenscript.org",
          initialProof: false
      }
    })
  }

  ngOnInit(): void {
    this.negotiator.negotiate();

    this.negotiator.on('tokens-selected', (issuerTokens: any) => {
      console.log('Got tokens...', issuerTokens);
    });

  }
}
